# Docker Compose para producción
# Usar con: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up

version: '3.8'

services:
  api:
    # Imagen optimizada para producción
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: production
    
    # Sin hot reload en producción
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--workers", "4"]
    
    # Variables de entorno para producción
    environment:
      - ENVIRONMENT=production
      - DEBUG=False
    
    # Sin volúmenes de desarrollo
    volumes: []
    
    # Configuración de recursos
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    
    # Política de reinicio más estricta
    restart: always

  nginx:
    # Configuración de producción para nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend:/usr/share/nginx/html:ro
    
    # Configuración de recursos
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 128M
        reservations:
          cpus: '0.10'
          memory: 64M
    
    restart: always