services:
  - type: web
    name: arman-travel-web
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt && cp -r ./frontend ./backend/
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: arman-travel-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: RECIPIENT_EMAIL
        value: info.armansolutions@gmail.com
      - key: WHATSAPP_NUMBER
        value: "1132551565"
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false

databases:
  - name: arman-travel-db
    databaseName: arman_travel
    user: arman_user
    plan: free