services:
  - type: web
    name: arman-travel
    env: python
    buildCommand: echo "Build completed"
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASSWORD
        sync: false

  - type: pserv
    name: arman-travel-postgres
    env: postgresql
    plan: free
    databaseName: arman_travel
    databaseUser: arman_user